{% set name = "levenshtein-search" %}
{% set version = "1.4.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Levenshtein_search-{{ version }}.tar.gz
  sha256: 323eb087008ff6ed1fd56c8c0efbedc15ac6fd59966a693556a2f314cd4d02c7

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - Levenshtein_search
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mattandahalfew/Levenshtein_search
  summary: Search through documents for approximately matching strings
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
    - izahn
